#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: kubuntu-studio
    username: oem
    password: "password"
  locale: de_DE.UTF-8
  keyboard:
    layout: de
  late-commands:
    - curtin in-target --target=/target -- apt-get update
    - curtin in-target --target=/target -- apt-get install -y latte-dock
    - curtin in-target --target=/target -- mkdir -p /home/oem/.config/latte
    - curtin in-target --target=/target -- wget -O /home/oem/.config/latte/WhiteSur.layout.latte https://github.com/vinceliuice/WhiteSur-kde/raw/master/latte-dock/WhiteSur.layout.latte
    - curtin in-target --target=/target -- chown -R oem:oem /home/oem/.config/latte
    - curtin in-target --target=/target -- latte-dock --import-layout /home/oem/.config/latte/WhiteSur.layout.latte
  user-data:
    packages:
      - latte-dock
  oem-config:
    enable: true
